# Generated by Django 2.0.4 on 2018-06-06 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('poem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('dynasty', models.CharField(blank=True, max_length=20, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('yi_id', models.IntegerField(blank=True, null=True)),
                ('zhu_id', models.IntegerField(blank=True, null=True)),
                ('shang_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'poem',
                'managed': True,
            },
        ),
    ]
